config/routes.rb
Rails.application.routes.draw do
  get :restricted, to: 'welcome#restricted'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/whitelist.rb
class Whitelist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :verify_ip_address

  private

  def verify_ip_address
    head :unauthorized if Whitelist.find_by(ip_address: request.remote_ip).nil?
    # if Whitelist.find_by(ip_address: request.remote_ip).nil?
      # redirect_to root_path, alert: 'Unauthorized access.'
    # end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # skip_before_action :verify_ip_address, only: :index
  before_action :verify_ip_address, only: :restricted
  def index
  end

  def restricted
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Template</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>

    <%= link_to 'Welcome', root_path, class: 'btn btn-primary' %>
    <%= link_to 'Restricted', restricted_path, class: 'btn btn-primary' %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<p>request.remote_ip: <%= request.remote_ip %></p>

app/views/welcome/restricted.html.erb
<h1>Welcome#restricted</h1>
<p>Find me in app/views/welcome/restricted.html.erb</p>

<p>request.remote_ip: <%= request.remote_ip %></p>